set ::HM_Framework::Settings::Keys::p_normal_key_proc(A) "{hm_pushpanel {automesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(B) "*view_restoreprevious";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(C) "{hm_pushpanel {check elems}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(D) "{hm_pushpanel {distance}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(E) "{hm_pushpanel {edit element}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Right) "hm_viewright";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F) "hm_viewfit";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(G) "hm_callglobalpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(H) "{hm_pushpanel {mask}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(I) "{hm_pushpanel {qualityindex}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(J) "{hm_pushpanel {scale}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(K) "{hm_pushpanel {rotate}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(L) "{hm_pushpanel {position}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(M) "{hm_pushpanel {midsurface}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(N) "{hm_pushpanel {defeature}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(O) "hm_calloptionspanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F10) "{hm_pushpanel {rename}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F11) "{hm_pushpanel {reorder}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(P) "{hm_pushpanel {project}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F12) "{hm_pushpanel {renumber}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Q) "{hm_pushpanel {quick edit}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(R) "{hm_pushpanel {rebuild mesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(S) "{hm_pushpanel {smooth}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(space) "hm_viewisometric";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(T) "{hm_pushpanel {tetramesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(U) "{hm_pushpanel {temp nodes}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(V) "hm_callviewpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(W) "hm_callplotwindowpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(X) "hm_callvispanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Y) "{hm_pushpanel {delete} }";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Z) "{hm_pushpanel {elem offset}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Down) "hm_viewdown";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(a) "{hm_pushpanel {automesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(b) "*view_restoreprevious";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(c) "{hm_pushpanel {check elems}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(d) "{hm_pushpanel {distance}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(e) "{hm_pushpanel {edit element}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(f) "hm_viewfit";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(g) "hm_callglobalpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F1) "{hm_pushpanel {quick edit}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F2) "{hm_pushpanel {automesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(h) "{hm_pushpanel {mask}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F3) "{hm_pushpanel {smooth}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(i) "{hm_pushpanel {qualityindex}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(j) "{hm_pushpanel {scale}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F4) "{hm_pushpanel {qualityindex}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(k) "{hm_pushpanel {rotate}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F5) "{hm_pushpanel {check elems}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Left) "hm_viewleft";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(l) "{hm_pushpanel {position}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F6) "{hm_pushpanel {split}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(plus) "hm_zoomin";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F7) "{hm_pushpanel {translate}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(Up) "hm_viewup";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(m) "{hm_pushpanel {midsurface}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(n) "{hm_pushpanel {defeature}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F8) "{hm_pushpanel {reflect}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(o) "hm_calloptionspanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(F9) "{hm_pushpanel {organize}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(p) "{hm_pushpanel {project}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(q) "{hm_pushpanel {quick edit}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(r) "{hm_pushpanel {rebuild mesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(s) "{hm_pushpanel {smooth}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(t) "{hm_pushpanel {tetramesh}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(u) "{hm_pushpanel {temp nodes}}";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(v) "hm_callviewpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(w) "hm_callplotwindowpanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(x) "hm_callvispanel";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(y) "{hm_pushpanel {delete} }";
set ::HM_Framework::Settings::Keys::p_normal_key_proc(z) "{hm_pushpanel {elem offset}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(C) "{hm_pushpanel {connectors}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(D) "hm_calldisplaypanel";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(E) "{hm_pushpanel {edge edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F) "{hm_pushpanel {find}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(H) "{hm_pushpanel {solid map}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(L) "{hm_pushpanel {line edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(M) "{hm_pushpanel {midmesh}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(N) "{hm_pushpanel {node edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(O) "{hm_pushpanel {solid edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(P) "{hm_pushpanel {point edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(R) "{hm_pushpanel {replace}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(S) "{hm_pushpanel {surface edit}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(T) "{hm_pushpanel {CFD tetramesh}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F1) "{hm_pushpanel {check elems}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F2) "{hm_pushpanel {edges}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F3) "{hm_pushpanel {faces}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F4) "{hm_pushpanel {normals}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F5) "{hm_pushpanel {dependency}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F6) "{hm_pushpanel {penetration}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F7) "{hm_pushpanel {count}}";
set ::HM_Framework::Settings::Keys::p_shift_key_proc(F8) "{hm_pushpanel {mass calc}}";
set ::HM_Framework::Settings::Keys::p_shift_key_file(M) "midmesh";
set ::HM_Framework::Settings::Keys::p_shift_key_file(F9) "This shortcut relates to create material and property sections";
set ::HM_Framework::Settings::Keys::p_control_key_proc(E) "{hm_pushpanel {edges}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Right) "hm_viewcw";
set ::HM_Framework::Settings::Keys::p_control_key_proc(L) "{hm_pushpanel {lines}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(N) "{hm_pushpanel {nodes}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(O) "{hm_pushpanel {solids}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(P) "{hm_pushpanel {points}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(R) "{hm_callspecialpanel {spherical clipping}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(S) "{hm_pushpanel {surfaces}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Y) "{if {1 == 1} {::hm::undoredo::PerformRedo}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Z) "{if {1 == 1} {::hm::undoredo::PerformUndo}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Down) "hm_viewreverse";
set ::HM_Framework::Settings::Keys::p_control_key_proc(e) "{hm_pushpanel {edges}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(F1) "hm_screencopy";
set ::HM_Framework::Settings::Keys::p_control_key_proc(F2) "hm_screenfile";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Left) "hm_viewccw";
set ::HM_Framework::Settings::Keys::p_control_key_proc(l) "{hm_pushpanel {lines}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(F6) "hm_jpegfile";
set ::HM_Framework::Settings::Keys::p_control_key_proc(Up) "hm_viewreverse";
set ::HM_Framework::Settings::Keys::p_control_key_proc(n) "{hm_pushpanel {nodes}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(o) "{hm_pushpanel {solids}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(p) "{hm_pushpanel {points}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(r) "{hm_callspecialpanel {spherical clipping}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(s) "{hm_pushpanel {surfaces}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(y) "{if {1 == 1} {::hm::undoredo::PerformRedo}}";
set ::HM_Framework::Settings::Keys::p_control_key_proc(z) "{if {1 == 1} {::hm::undoredo::PerformUndo}}";
set ::HM_Framework::Settings::Keys::p_control_shift_key_proc(S) "{::HM_Framework::p_VCToggleSate selector}";
